#!/usr/bin/env python3
"""Generate `Sources/WhisperCore/ChineseScript.swift` from the vendored OpenCC table (F245).

    python3 Scripts/generate-chinese-script.py            # write the Swift file
    python3 Scripts/generate-chinese-script.py --check     # fail if it is stale

The app needs to tell Traditional from Simplified and could not: `TranscriptLanguage.dominant`
answers "which language", and the two scripts are one language. That is why the refinement guard
accepts a Traditional dictation returned as Simplified while refusing the same input returned as
English — measured on 2026-09-17, and the guard accepted it.

The data is the same `st_characters.txt` the F244 scorer vendors, so the app and the bench cannot
disagree about what counts as a script change. Generated into Swift rather than read at runtime
because `WhisperCore` is Foundation-only and has no resource bundle.

**Parsing, which took three attempts.** The file is `<simplified>\\t<alt> <alt> …` — tab first, then
*space-separated* alternatives. A character is Simplified-only only when none of its alternatives is
itself: `了 → 了 瞭` and `出 → 出 齣` are shared and must not count, while `个 → 個 箇` and
`们 → 們` do. Comparing the key against the unsplit remainder made every shared character look
Simplified-only, which would have made the directional check below fire on ordinary Traditional
text. The count is the check: 3810 Simplified-only characters, exactly what
`score.SIMPLIFIED_CHARACTERS` computes independently.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TABLE = os.path.join(HERE, "bench", "fidelity", "st_characters.txt")
OUTPUT = os.path.join(HERE, "..", "Sources", "WhisperCore", "ChineseScript.swift")

EXPECTED_SIMPLIFIED = 3810


def sets_from_table(path=TABLE):
    simplified, traditional = set(), set()
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if not line or line.startswith("#") or "\t" not in line:
                continue
            key, rest = line.split("\t", 1)
            alternatives = rest.split()
            if key in alternatives:
                continue  # shared between the scripts
            simplified.add(key)
            for form in alternatives:
                traditional.update(form)
    return simplified, traditional - simplified


def render(simplified, traditional):
    return f'''// Generated by Scripts/generate-chinese-script.py from Scripts/bench/fidelity/st_characters.txt.
// Do not edit by hand: `python3 Scripts/generate-chinese-script.py` regenerates it, and
// `ChineseScriptFixtureTests` fails when it is stale.
//
// F245. The app could not tell Traditional from Simplified — `TranscriptLanguage.dominant` answers
// "which language", and the two scripts are one language — so the refinement guard accepted a
// Traditional dictation returned as Simplified while refusing the same input returned as English.
// The data is the table the F244 scorer vendors, so the app and the bench agree on what a script
// change is.

import Foundation

public enum ChineseScript {{
    /// Characters that exist only in Simplified: every OpenCC mapping whose Traditional
    /// alternatives do not include the character itself. `了`, `出` and `才` are therefore absent —
    /// they are shared, and treating them as Simplified would make ordinary Traditional text look
    /// converted.
    public static let simplifiedOnly: Set<Character> = Set("{''.join(sorted(simplified))}")

    /// The Traditional forms of those mappings, minus anything also Simplified-only.
    public static let traditionalOnly: Set<Character> = Set("{''.join(sorted(traditional))}")
}}
'''


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    simplified, traditional = sets_from_table()
    if len(simplified) != EXPECTED_SIMPLIFIED:
        raise SystemExit(
            f"expected {EXPECTED_SIMPLIFIED} Simplified-only characters, got {len(simplified)}. "
            "The table or the parse changed; check against score.SIMPLIFIED_CHARACTERS before "
            "updating this number."
        )
    rendered = render(simplified, traditional)
    path = os.path.normpath(OUTPUT)
    if "--check" in argv:
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if current != rendered:
            raise SystemExit(f"{path} is stale; run python3 Scripts/generate-chinese-script.py")
        print(f"{os.path.basename(path)} is current "
              f"({len(simplified)} Simplified-only, {len(traditional)} Traditional-only).")
        return 0
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {path}: {len(simplified)} Simplified-only, {len(traditional)} Traditional-only")
    return 0


if __name__ == "__main__":
    sys.exit(main())
