// Sources/WhisperMeet/Dictation/TextInjector.swift
import AppKit
import ApplicationServices
import CoreGraphics
import os

/// Delivers dictated text (F516, which replaced F425's mechanism with the standard one).
///
/// **Auto-paste** pastes through the clipboard with ⌘V. That is what Wispr Flow, Superwhisper and
/// VoiceInk all do, because it is the one insertion that works in every app and under every input
/// method: an Accessibility write reports success in Chromium and Electron fields without
/// inserting anything, and synthesized typing is intercepted by the Pinyin input method. The
/// clipboard is only borrowed:
///
/// 1. At paste time the user's clipboard is copied — every item, every representation.
/// 2. The dictation is written, marked transient so clipboard-history tools skip it, and ⌘V is
///    posted.
/// 3. If a text field had focus, the copy goes back `restoreDelay` later — unless something else
///    has written the clipboard since, which then wins. If no text field had focus, the dictation
///    stays on the clipboard as an ordinary copy: it went nowhere, and that is where the user will
///    look for it.
///
/// **Clipboard only** — auto-paste off, or no ⌘V possible (no Accessibility): the text is written
/// and left, because the clipboard is the delivery.
///
/// Where a restore cannot be shown to be right — a clipboard marked concealed, one that could not
/// be read in full, a system setting that would ask before the read — the dictation is left on the
/// clipboard, and it is in the dictation history either way.
@MainActor
final class TextInjector {
    enum Delivery { case pasted, clipboard }

    /// How long after ⌘V the clipboard is put back. Nothing tells us the target app has consumed
    /// the paste, and restoring too early makes it paste the OLD content — worse than not restoring.
    /// Erring long costs little: anything the user copies inside the window wins over the restore.
    nonisolated static let defaultRestoreDelay: TimeInterval = 1.5

    /// The nspasteboard.org markers that tell clipboard-history tools not to record an item.
    nonisolated static let transientMarkers: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard: NSPasteboard
    private let restoreDelay: TimeInterval
    private let canSynthesizePaste: () -> Bool
    private let focusedTextField: () -> FocusedTextField.Probe
    private let synthesizePaste: () -> Bool
    private let schedule: (TimeInterval, @escaping @MainActor () -> Void) -> Void
    private let log = Logger(subsystem: "com.whispermeet.app", category: "dictation")

    /// The user's clipboard while a restore is scheduled, and the `changeCount` our write produced.
    /// A second dictation inside the window restores THIS rather than copying the clipboard, which
    /// at that moment holds the first dictation.
    private var pending: (snapshot: PasteboardSnapshot, written: Int)?
    /// Bumped by every delivery, so a restore scheduled by an earlier paste does nothing once a
    /// later write has taken the clipboard over.
    private var generation = 0

    init(
        pasteboard: NSPasteboard = .general,
        restoreDelay: TimeInterval = TextInjector.defaultRestoreDelay,
        canSynthesizePaste: @escaping () -> Bool = { AXIsProcessTrusted() },
        focusedTextField: @escaping () -> FocusedTextField.Probe = FocusedTextField.probe,
        synthesizePaste: @escaping () -> Bool = TextInjector.postCommandV,
        schedule: @escaping (TimeInterval, @escaping @MainActor () -> Void) -> Void = TextInjector.scheduleOnMain
    ) {
        self.pasteboard = pasteboard
        self.restoreDelay = restoreDelay
        self.canSynthesizePaste = canSynthesizePaste
        self.focusedTextField = focusedTextField
        self.synthesizePaste = synthesizePaste
        self.schedule = schedule
    }

    func deliver(_ text: String, autoPaste: Bool) -> Delivery {
        generation &+= 1
        let carried = pending.flatMap { pasteboard.changeCount == $0.written ? $0.snapshot : nil }
        pending = nil

        guard autoPaste, canSynthesizePaste() else {
            write(text, transient: false)
            return .clipboard
        }
        let target = focusedTextField()
        // Taken now, at paste time: an item that arrived while the user was speaking — from the
        // iPhone, say — is the clipboard they expect back. Only when it will be given back.
        let snapshot = target.isTextField ? (carried ?? takeSnapshot()) : nil
        write(text, transient: snapshot != nil)
        let written = pasteboard.changeCount
        guard synthesizePaste() else { return .clipboard }

        guard target.isTextField else {
            log.notice("pasted into \(target.summary, privacy: .public), not a text field: dictation left on the clipboard")
            return .clipboard
        }
        guard let snapshot else { return .pasted }
        pending = (snapshot, written)
        let scheduled = generation
        schedule(restoreDelay) { [weak self] in self?.restoreIfUnchanged(generation: scheduled) }
        return .pasted
    }

    private func write(_ text: String, transient: Bool) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if transient {
            for marker in Self.transientMarkers { item.setData(Data(), forType: marker) }
        }
        pasteboard.writeObjects([item])
    }

    private func takeSnapshot() -> PasteboardSnapshot? {
        guard mayReadContents() else {
            log.notice("clipboard not copied for restore: the system would ask before reading it")
            return nil
        }
        switch PasteboardSnapshot.read(from: pasteboard) {
        case let .success(snapshot):
            // Type NAMES only, never content: enough to tell a Universal Clipboard item from a local one.
            let types = snapshot.items.map { $0.map(\.type).joined(separator: ",") }.joined(separator: " | ")
            log.notice("clipboard copied for restore: \(snapshot.items.count, privacy: .public) item(s): \(types, privacy: .public)")
            return snapshot
        case let .failure(refusal):
            log.notice("clipboard not copied for restore: \(refusal.rawValue, privacy: .public)")
            return nil
        }
    }

    private func restoreIfUnchanged(generation scheduled: Int) {
        guard scheduled == generation, let (snapshot, written) = pending else { return }
        pending = nil
        guard pasteboard.changeCount == written else {
            log.notice("clipboard not restored: it was written to after the dictation was pasted")
            return
        }
        guard let staged = snapshot.stagedItems() else {
            log.error("clipboard not restored: a saved representation was refused")
            return
        }
        pasteboard.clearContents()
        // An empty snapshot is an empty clipboard, which the clear above has already restored.
        if !staged.isEmpty, !pasteboard.writeObjects(staged) {
            log.error("clipboard not restored: the pasteboard refused the saved items")
            return
        }
        log.notice("clipboard restored after dictation paste")
    }

    private func mayReadContents() -> Bool {
        if #available(macOS 15.4, *) {
            return Self.allowsSnapshot(accessBehavior: pasteboard.accessBehavior)
        }
        return true // no programmatic-access control exists before macOS 15.4
    }

    /// Whether to read the clipboard for a restore, given the user's pasteboard access setting.
    /// `.ask` would raise the system prompt on every dictation and `.alwaysDeny` returns nothing that
    /// can be told from an empty clipboard, so neither is read; the dictation then stays on the
    /// clipboard. `.default` is read (F425's choice, kept): one possible prompt over a restore that
    /// never works.
    @available(macOS 15.4, *)
    nonisolated static func allowsSnapshot(accessBehavior: NSPasteboard.AccessBehavior) -> Bool {
        switch accessBehavior {
        case .alwaysAllow, .default: true
        case .ask, .alwaysDeny: false
        @unknown default: false
        }
    }

    /// Synthesizes ⌘V into the focused app. False when it cannot: no Accessibility, or the events
    /// could not be created.
    nonisolated static func postCommandV() -> Bool {
        let vKey: CGKeyCode = 9 // kVK_ANSI_V
        guard AXIsProcessTrusted(),
              let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false) else {
            return false
        }

        // Let the pasteboard settle before the synthetic paste.
        usleep(20_000)

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.post(tap: .cgAnnotatedSessionEventTap)
        keyUp.post(tap: .cgAnnotatedSessionEventTap)
        return true
    }

    nonisolated static func scheduleOnMain(
        after delay: TimeInterval,
        _ work: @escaping @MainActor () -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            MainActor.assumeIsolated { work() }
        }
    }
}
