// Sources/WhisperMeet/Dictation/TextInjector.swift
import AppKit
import ApplicationServices
import Carbon
import CoreGraphics
import os

/// Delivers dictated text (F516, which replaced F425's mechanism with the standard one).
///
/// **Auto-paste** pastes through the clipboard with ⌘V. That is what Wispr Flow, Superwhisper and
/// VoiceInk all do, because it is the one insertion that works in every app and under every input
/// method: an Accessibility write reports success in Chromium and Electron fields without
/// inserting anything, and synthesized typing is intercepted by the Pinyin input method. The
/// clipboard is only borrowed:
///
/// 1. The user's clipboard is copied — every item, every representation, up to 32 MiB — off the
///    main thread when the dictation starts, and used at paste time only if the clipboard has not
///    changed since; if it has, it is copied again then (F601, `captureWillStart`).
/// 2. The dictation is written, marked transient so clipboard-history tools skip it, and ⌘V is
///    posted.
/// 3. If a text field had focus, the copy goes back `restoreDelay` later — unless something else
///    has written the clipboard since, which then wins. If no text field could be seen, the
///    dictation stays on the clipboard as an ordinary copy: it may have gone nowhere, and that is
///    where the user will look for it. It is still reported as pasted (F600), because the ⌘V was
///    sent and an app can hide its field from Accessibility.
///
/// **Clipboard only** — auto-paste off, or no ⌘V possible (no Accessibility): the text is written
/// and left, because the clipboard is the delivery.
///
/// **Not pasted** (F445) — secure input at the press or at delivery: never pasted, even with
/// auto-paste off, and not written to the clipboard (F586) — the pill offers Copy, which writes it
/// concealed (`copyConcealed`). A different app in front than the one the key was pressed in: left
/// as an ordinary copy.
///
/// Where a restore cannot be shown to be right — a clipboard marked concealed, one that could not
/// be read in full, one over the size cap, a system setting that would ask before the read — the
/// dictation is left on the clipboard, and it is in the dictation history either way.
@MainActor
final class TextInjector {
    enum Delivery: Equatable {
        case pasted, clipboard
        /// ⌘V was posted, but no text field could be seen to take it — an app can hide its field
        /// from Accessibility — so the clipboard is not given back and the dictation is on it too
        /// (F600). A paste, not a copy: telling the user to press ⌘V would paste it twice.
        case pastedUnconfirmed
        /// Left on the clipboard: the app the dictation was started in is no longer in front (F445).
        case appChanged
        /// Secure input (F445): never pasted or logged, and not written to the clipboard (F586).
        case secureInput
        /// As `secureInput`, when the reason is secure event input and the window server names an
        /// app for it — the app in front when it came on, a hint for the pill, not the owner (F585).
        case secureKeyboardEntry(app: String)

        /// Secure input, for any reason: never pasted, never written to the history.
        var isSecure: Bool {
            switch self {
            case .secureInput, .secureKeyboardEntry: true
            case .pasted, .pastedUnconfirmed, .clipboard, .appChanged: false
            }
        }

        /// ⌘V went to the app the dictation was made in, so the history records a paste (F600).
        /// The history has no third value for "pasted, not seen to land": a new case would read as
        /// "Recorded by a newer version" in the builds since F266, would make the whole log
        /// unreadable in builds before F251, and the text was pasted.
        var wasPasted: Bool {
            switch self {
            case .pasted, .pastedUnconfirmed: true
            case .clipboard, .appChanged, .secureInput, .secureKeyboardEntry: false
            }
        }
    }

    /// How long after ⌘V the clipboard is put back. Nothing tells us the target app has consumed
    /// the paste, and restoring too early makes it paste the OLD content — worse than not restoring.
    /// Erring long costs little: anything the user copies inside the window wins over the restore.
    nonisolated static let defaultRestoreDelay: TimeInterval = 1.5

    /// The nspasteboard.org markers that tell clipboard-history tools not to record an item.
    nonisolated static let transientMarkers: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// A clipboard larger than this is not held, so it is not restored (F425's number, restored by
    /// F601). Text of any realistic length is far below it; a 4032 × 3024 image offered as TIFF and
    /// PNG measured 88.8 MB (2026-09-28), so a copied photo is not given back. There its first
    /// representation, the 48.8 MB TIFF, crossed the cap alone, and reading stops there.
    nonisolated static let defaultMaximumSnapshotBytes = 32 * 1024 * 1024

    /// A pasteboard handed to the snapshot queue. `NSPasteboard` is not `Sendable`; F425 read it off
    /// the main thread the same way.
    struct PasteboardHandle: @unchecked Sendable {
        let pasteboard: NSPasteboard
    }

    /// Reads a snapshot under a byte cap: `PasteboardSnapshot.read`, or a test's stand-in that
    /// also records which thread it ran on.
    typealias SnapshotReader = @Sendable (PasteboardHandle, Int) -> Result<PasteboardSnapshot, PasteboardSnapshot.Refusal>

    private let pasteboard: NSPasteboard
    private let restoreDelay: TimeInterval
    private let maximumSnapshotBytes: Int
    private let readSnapshot: SnapshotReader
    private let canSynthesizePaste: () -> Bool
    private let focusedTextField: () -> FocusedTextField.Probe
    private let synthesizePaste: () -> Bool
    private let schedule: (TimeInterval, @escaping @MainActor () -> Void) -> Void
    private let log = Logger(subsystem: "com.whispermeet.app", category: "dictation")

    /// The user's clipboard while a restore is scheduled, and the `changeCount` our write produced.
    /// A second dictation inside the window restores THIS rather than copying the clipboard, which
    /// at that moment holds the first dictation.
    private var pending: (snapshot: PasteboardSnapshot, written: Int)?
    /// Bumped by every delivery, so a restore scheduled by an earlier paste does nothing once a
    /// later write has taken the clipboard over.
    private var generation = 0

    init(
        pasteboard: NSPasteboard = .general,
        restoreDelay: TimeInterval = TextInjector.defaultRestoreDelay,
        maximumSnapshotBytes: Int = TextInjector.defaultMaximumSnapshotBytes,
        readSnapshot: @escaping SnapshotReader = { PasteboardSnapshot.read(from: $0.pasteboard, maximumBytes: $1) },
        canSynthesizePaste: @escaping () -> Bool = { AXIsProcessTrusted() },
        focusedTextField: @escaping () -> FocusedTextField.Probe = FocusedTextField.probe,
        synthesizePaste: @escaping () -> Bool = TextInjector.postCommandV,
        schedule: @escaping (TimeInterval, @escaping @MainActor () -> Void) -> Void = TextInjector.scheduleOnMain
    ) {
        self.pasteboard = pasteboard
        self.restoreDelay = restoreDelay
        self.maximumSnapshotBytes = maximumSnapshotBytes
        self.readSnapshot = readSnapshot
        self.canSynthesizePaste = canSynthesizePaste
        self.focusedTextField = focusedTextField
        self.synthesizePaste = synthesizePaste
        self.schedule = schedule
    }

    /// What the delivery will be checked against, taken when the dictation starts (F445).
    func target() -> FocusedTextField.Probe {
        focusedTextField()
    }

    /// The off-main clipboard read `captureWillStart` began, if any — exposed so a test can await it
    /// instead of sleeping.
    private(set) var clipboardPrefetch: Task<Void, Never>?
    /// What that read came back with, and the `changeCount` it started under. It stands for the
    /// clipboard at paste time only while the live count is still that one.
    private var prefetched: (result: Result<PasteboardSnapshot, PasteboardSnapshot.Refusal>, changeCount: Int)?
    /// Bumped whenever a read's answer stops being wanted, so a late one is dropped.
    private var prefetchGeneration = 0

    /// One serial queue, so a read blocked on a slow promise (a phone that has gone out of range)
    /// makes the next dictation's read wait rather than pile a second blocked thread beside it (F425).
    ///
    /// Every other read and write of the pasteboard here goes through it too, with `sync` (F657):
    /// the early read may still be running at paste time, and the main thread must not read,
    /// clear or write the same pasteboard while the queue is inside `data(forType:)`. Waiting for
    /// it is no slower than F516's paste-time read on the main thread, which it replaces.
    nonisolated private static let snapshotQueue = DispatchQueue(
        label: "com.whispermeet.dictation.clipboard-snapshot",
        qos: .userInitiated
    )

    /// Called when a dictation starts recording: returns `target()`, and starts copying the
    /// clipboard off the main thread when this dictation will be pasted into a text field and so
    /// may give it back (F601).
    ///
    /// F516 made that copy at paste time, on the main actor, and measured nothing. Measured
    /// 2026-09-28 in a separate process: reading a 12-megapixel image another app provides lazily
    /// took 2.5 s, and one it provided eagerly 22 ms — time F516 would spend on the run loop that
    /// hosts the hotkey tap. Read here, it overlaps the user speaking. At paste time it is used
    /// only if the clipboard's `changeCount` is still the one it was read under — so the clipboard
    /// given back is still the one the user had when the paste happened, which is F516's rule; if
    /// it changed (an item arriving from the iPhone while they spoke), or the read has not come
    /// back yet, it is read again then, after the early read has finished (F657).
    func captureWillStart(autoPaste: Bool) -> FocusedTextField.Probe {
        discardClipboardPrefetch()
        let target = target()
        guard autoPaste, target.isTextField, !target.isSecure, canSynthesizePaste(), mayReadContents() else {
            return target
        }
        // The clipboard still holds the previous dictation, whose restore will carry over.
        if let pending, pasteboard.changeCount == pending.written { return target }
        let generation = prefetchGeneration
        let handle = PasteboardHandle(pasteboard: pasteboard)
        let maximumBytes = maximumSnapshotBytes
        let read = readSnapshot
        clipboardPrefetch = Task { [weak self] in
            let outcome = await withCheckedContinuation { continuation in
                Self.snapshotQueue.async {
                    let changeCount = handle.pasteboard.changeCount
                    continuation.resume(returning: (read(handle, maximumBytes), changeCount))
                }
            }
            guard let self, generation == self.prefetchGeneration else { return }
            self.prefetched = outcome
        }
        return target
    }

    /// Drops a clipboard copy no delivery used, and any answer still on its way.
    func discardClipboardPrefetch() {
        prefetchGeneration &+= 1
        prefetched = nil
        clipboardPrefetch = nil
    }

    /// `pressed` is `target()` as it was when the key went down (F445), so the paste goes where the
    /// user started or nowhere. Nil skips both press-time checks.
    func deliver(_ text: String, autoPaste: Bool, pressedIn pressed: FocusedTextField.Probe? = nil) -> Delivery {
        let early = prefetched
        discardClipboardPrefetch()
        let target = focusedTextField()
        // What was judged, so a real app's secure-input and text-field reading can be checked
        // against what the user saw (F585; the probe's reads have no test that can see a real app).
        log.notice("delivery target: \(target.summary, privacy: .public)")

        // Secure input at the press or now: the words may be a password, or a password prompt has
        // taken focus and would receive a sentence as one. Never pasted, whatever auto-paste says,
        // and not written to the clipboard either (F586, the user's decision of 2026-09-28): the
        // Concealed and Transient markers are advisory, and any process can read the pasteboard.
        // The controller holds the text for the pill's Copy button and keeps it out of the history.
        // Touches nothing here — a restore owed to the previous paste still goes ahead.
        if let secure = target.secureInput ?? pressed?.secureInput {
            log.notice("secure input (\(String(describing: secure), privacy: .public)): dictation not pasted and not written to the clipboard")
            if case let .keyboardEntry(app?) = secure { return .secureKeyboardEntry(app: app) }
            return .secureInput
        }
        generation &+= 1
        let carried = pending.flatMap { pasteboard.changeCount == $0.written ? $0.snapshot : nil }
        pending = nil
        guard autoPaste, canSynthesizePaste() else {
            write(text, markers: [])
            return .clipboard
        }
        // The user moved to another app while it was transcribing: ⌘V would land in whatever they
        // are doing now. Left on the clipboard, where they can paste it where they meant.
        if let started = pressed?.processIdentifier, let now = target.processIdentifier, started != now {
            write(text, markers: [])
            log.notice("frontmost app changed since the press (now \(target.summary, privacy: .public)): dictation left on the clipboard")
            return .appChanged
        }
        // The clipboard as it is at paste time: an item that arrived while the user was speaking —
        // from the iPhone, say — is the clipboard they expect back. Only when it will be given back.
        let snapshot = target.isTextField ? (carried ?? clipboardSnapshot(readEarly: early)) : nil
        write(text, markers: snapshot != nil ? Self.transientMarkers : [])
        let written = pasteboard.changeCount
        guard synthesizePaste() else { return .clipboard }

        // Sent, so reported as a paste (F600): the app may hide its field from Accessibility, and
        // a "press ⌘V" notice would then paste it twice. The clipboard is not given back, so the
        // dictation is also there.
        guard target.isTextField else {
            log.notice("pasted into \(target.summary, privacy: .public), not a text field: dictation left on the clipboard too")
            return .pastedUnconfirmed
        }
        guard let snapshot else { return .pasted }
        pending = (snapshot, written)
        let scheduled = generation
        schedule(restoreDelay) { [weak self] in self?.restoreIfUnchanged(generation: scheduled) }
        return .pasted
    }

    /// Writes a dictation made into secure input, on the user's explicit Copy from the pill (F586):
    /// their own act, so the pasteboard is written — still marked concealed and transient, so the
    /// clipboard-history tools that honour the markers neither show nor keep it. Like any write, it
    /// takes the clipboard over from a restore still owed to an earlier paste.
    func copyConcealed(_ text: String) {
        generation &+= 1
        pending = nil
        write(text, markers: Self.transientMarkers + [Self.concealedMarker])
        log.notice("secure-input dictation copied at the user's request, concealed")
    }

    /// The nspasteboard.org marker for a secret, which clipboard managers neither show nor keep.
    nonisolated static let concealedMarker = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// Writes on the snapshot queue, so an early read still in flight finishes first (F657).
    private func write(_ text: String, markers: [NSPasteboard.PasteboardType]) {
        let pasteboard = self.pasteboard
        Self.snapshotQueue.sync {
            pasteboard.clearContents()
            let item = NSPasteboardItem()
            item.setString(text, forType: .string)
            for marker in markers { item.setData(Data(), forType: marker) }
            pasteboard.writeObjects([item])
        }
    }

    /// The clipboard as it is now: the early read's answer while the clipboard is provably
    /// unchanged since it began — a refusal included, so a clipboard over the cap is not read a
    /// second time here (F601) — and otherwise a read at paste time, on the snapshot queue after
    /// any early read still on it, so the two never overlap (F657).
    private func clipboardSnapshot(readEarly early: (result: Result<PasteboardSnapshot, PasteboardSnapshot.Refusal>, changeCount: Int)?) -> PasteboardSnapshot? {
        if let early, early.changeCount == pasteboard.changeCount {
            return accept(early.result, when: "when the dictation started")
        }
        guard mayReadContents() else {
            log.notice("clipboard not copied for restore: the system would ask before reading it")
            return nil
        }
        let handle = PasteboardHandle(pasteboard: pasteboard)
        let read = readSnapshot
        let maximumBytes = maximumSnapshotBytes
        return accept(Self.snapshotQueue.sync { read(handle, maximumBytes) }, when: "at paste time")
    }

    private func accept(_ result: Result<PasteboardSnapshot, PasteboardSnapshot.Refusal>, when: String) -> PasteboardSnapshot? {
        switch result {
        case let .success(snapshot):
            // Type NAMES only, never content: enough to tell a Universal Clipboard item from a local one.
            let types = snapshot.items.map { $0.map(\.type).joined(separator: ",") }.joined(separator: " | ")
            log.notice("clipboard copied for restore \(when, privacy: .public): \(snapshot.items.count, privacy: .public) item(s): \(types, privacy: .public)")
            return snapshot
        case let .failure(refusal):
            log.notice("clipboard not copied for restore \(when, privacy: .public): \(refusal.rawValue, privacy: .public)")
            return nil
        }
    }

    private func restoreIfUnchanged(generation scheduled: Int) {
        guard scheduled == generation, let (snapshot, written) = pending else { return }
        pending = nil
        guard pasteboard.changeCount == written else {
            log.notice("clipboard not restored: it was written to after the dictation was pasted")
            return
        }
        guard let staged = snapshot.stagedItems() else {
            log.error("clipboard not restored: a saved representation was refused")
            return
        }
        // On the snapshot queue like every other write (F657).
        let pasteboard = self.pasteboard
        let accepted = Self.snapshotQueue.sync {
            pasteboard.clearContents()
            // An empty snapshot is an empty clipboard, which the clear above has already restored.
            return staged.isEmpty || pasteboard.writeObjects(staged)
        }
        guard accepted else {
            log.error("clipboard not restored: the pasteboard refused the saved items")
            return
        }
        log.notice("clipboard restored after dictation paste")
    }

    private func mayReadContents() -> Bool {
        if #available(macOS 15.4, *) {
            return Self.allowsSnapshot(accessBehavior: pasteboard.accessBehavior)
        }
        return true // no programmatic-access control exists before macOS 15.4
    }

    /// Whether to read the clipboard for a restore, given the user's pasteboard access setting.
    /// `.ask` would raise the system prompt on every dictation and `.alwaysDeny` returns nothing that
    /// can be told from an empty clipboard, so neither is read; the dictation then stays on the
    /// clipboard. `.default` is read (F425's choice, kept): one possible prompt over a restore that
    /// never works.
    @available(macOS 15.4, *)
    nonisolated static func allowsSnapshot(accessBehavior: NSPasteboard.AccessBehavior) -> Bool {
        switch accessBehavior {
        case .alwaysAllow, .default: true
        case .ask, .alwaysDeny: false
        @unknown default: false
        }
    }

    /// Synthesizes ⌘V into the focused app. False when it cannot: no Accessibility, or the events
    /// could not be created.
    nonisolated static func postCommandV() -> Bool {
        let vKey = commandVKeyCode()
        guard AXIsProcessTrusted(),
              let source = CGEventSource(stateID: .combinedSessionState),
              let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false) else {
            return false
        }

        // Let the pasteboard settle before the synthetic paste.
        usleep(20_000)

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.post(tap: .cgAnnotatedSessionEventTap)
        keyUp.post(tap: .cgAnnotatedSessionEventTap)
        return true
    }

    /// The key that types v with ⌘ held on the keyboard layout in use, so the synthesized paste is
    /// ⌘V on every layout (F489). A `CGEvent` names a key POSITION; the app receiving it turns that
    /// into a character through the current layout, and position 9 (`kVK_ANSI_V`) is v only on
    /// QWERTY-shaped layouts: under ⌘ it is k on Dvorak (⌘K clears Terminal's scrollback, opens
    /// Slack's switcher) and c on Turkish (⌘C copies over the dictation just placed on the
    /// clipboard). Asked under ⌘ rather than plain, because "Dvorak - QWERTY ⌘" puts shortcuts back
    /// on the QWERTY keys and Russian has no v except under ⌘.
    ///
    /// Position 9 when the layout cannot be read or has no v under ⌘ at all (Turkmen): what the
    /// paste always sent, and right on 246 of the 251 layouts macOS ships (measured 2026-09-25,
    /// `PasteKeyCodeTests`).
    nonisolated static func commandVKeyCode() -> CGKeyCode {
        guard let layout = currentKeyboardLayoutData() else { return 9 }
        return keyCode(typing: 0x76, withCommandIn: layout, keyboardType: UInt32(LMGetKbdType())) ?? 9
    }

    /// The 'uchr' data of the layout the user is typing through — with an input method selected, the
    /// layout that input method uses (TextInputSources.h). Nil when there is no current input source
    /// or the layout has only 'KCHR' data (none of the 251 installed here has).
    nonisolated static func currentKeyboardLayoutData() -> Data? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let raw = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        return Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue() as Data
    }

    /// The lowest key position (0–127) that `layoutData` maps to `character` with ⌘ held, or nil
    /// when none does. Pure: `UCKeyTranslate` over the given 'uchr' bytes and nothing read from the
    /// machine, which is what lets a test hand it a layout of its own. `keyboardType` is
    /// `LMGetKbdType()`'s value; a layout with no entry for it uses its default entry, and a table
    /// entry of 0xFFFE–0xFFFF is "no character" (UnicodeUtilities.h). No dead-key state is entered
    /// (`kUCKeyTranslateNoDeadKeysMask`), so every key is asked in the layout's base state.
    nonisolated static func keyCode(typing character: UniChar, withCommandIn layoutData: Data, keyboardType: UInt32) -> CGKeyCode? {
        layoutData.withUnsafeBytes { bytes -> CGKeyCode? in
            guard bytes.count >= MemoryLayout<UCKeyboardLayout>.size, let base = bytes.baseAddress else { return nil }
            let layout = base.assumingMemoryBound(to: UCKeyboardLayout.self)
            // UCKeyTranslate's modifierKeyState is `EventRecord.modifiers >> 8`; ⌘ is bit 0 of it.
            let command = UInt32((cmdKey >> 8) & 0xFF)
            for key in 0..<128 {
                var deadKeyState: UInt32 = 0
                var length = 0
                var output = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(
                    layout, UInt16(key), UInt16(kUCKeyActionDown), command, keyboardType,
                    OptionBits(kUCKeyTranslateNoDeadKeysMask), &deadKeyState, output.count, &length, &output
                )
                if status == noErr, length == 1, output[0] == character { return CGKeyCode(key) }
            }
            return nil
        }
    }

    nonisolated static func scheduleOnMain(
        after delay: TimeInterval,
        _ work: @escaping @MainActor () -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            MainActor.assumeIsolated { work() }
        }
    }
}
